# Generated by Django 5.2.16 on 2026-08-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_line_2',
            new_name='address_line_1',
        ),
    ]
