# Generated by Django 5.2.16 on 2026-08-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_address_line_2_address_address_line_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
