# Generated by Django 5.2.16 on 2026-08-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_address_address_line_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='area',
            new_name='village',
        ),
    ]
