# Generated by Django 5.2.16 on 2026-08-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gateway_payment_id',
            new_name='gateway_order_id',
        ),
    ]
